FROM nginx:1.19.9-alpine
LABEL maintainer="Anderson R M Jesus <anderrodrigo@gmail.com>"
COPY . 'X:\Cloud\Gdrive\01 - Projetos\02 - Proj Canadá\02 - Curso Capacitação\02 - Docker\01 - Material de apoio\secao07'
EXPOSE 80 
